spring:
  datasource:
    url: jdbc:mysql://localhost:3306/websocket?createDatabaseIfNotExist=true
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true